'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/browser';
import { getAccounts, getTransactions, getWorkspaceId } from '@/repositories/finance';
import { formatCurrency } from '@/lib/money';
import { calculateAccountBalance } from '@/lib/domain/finance';

type Account = { id:string; name:string; initial_balance:number; active:boolean }; type Transaction = { id:string; type:'INCOME'|'EXPENSE'|'TRANSFER'; description:string; amount:number; transaction_date:string; competence_date:string; status:string; account_id:string|null };
export function DashboardClient() { const client=createClient(); const [accounts,setAccounts]=useState<Account[]>([]); const [transactions,setTransactions]=useState<Transaction[]>([]); useEffect(()=>{void (async()=>{const workspace=await getWorkspaceId(client);if(!workspace)return;const [a,t]=await Promise.all([getAccounts(client,workspace),getTransactions(client,workspace)]);setAccounts((a.data as Account[])||[]);setTransactions((t.data as Transaction[])||[]);})();},[]);const now=new Date();const month=now.toISOString().slice(0,7);const current=transactions.filter(t=>t.competence_date.startsWith(month));const received=current.filter(t=>t.type==='INCOME'&&t.status==='RECEIVED').reduce((s,t)=>s+Number(t.amount),0);const paid=current.filter(t=>t.type==='EXPENSE'&&t.status==='PAID').reduce((s,t)=>s+Number(t.amount),0);const pending=current.filter(t=>(t.type==='INCOME'||t.type==='EXPENSE')&&(t.status==='PENDING'||t.status==='OVERDUE'));const pendingExpenses=pending.filter(t=>t.type==='EXPENSE').reduce((s,t)=>s+Number(t.amount),0);const balances=accounts.filter(a=>a.active).map(a=>calculateAccountBalance(Number(a.initial_balance),transactions.filter(t=>t.account_id===a.id).map(t=>({type:t.type,amount:Number(t.amount),status:t.status as 'PENDING'|'PAID'|'RECEIVED'|'OVERDUE'|'CANCELLED'}))));const total=balances.reduce((s,v)=>s+v,0);return <><section className="balance-card"><div className="balance-heading"><span>Saldo disponível</span><span className="status-dot">● dados reais</span></div><strong>{formatCurrency(total)}</strong><div className="balance-footer"><span>Saldo das contas ativas</span><span>Disponível estimado {formatCurrency(total-pendingExpenses)}</span></div></section><section className="month-section"><div className="section-title"><div><h2>Visão de setembro</h2><span className="muted">Por competência</span></div></div><div className="metrics"><div><span>Receitas recebidas</span><strong className="income">{formatCurrency(received)}</strong></div><div><span>Despesas pagas</span><strong>{formatCurrency(paid)}</strong></div><div><span>Pendentes</span><strong>{formatCurrency(pendingExpenses)}</strong></div></div></section><section className="list-card recent-list"><div className="section-title"><h2>Últimos lançamentos</h2><a className="muted" href="/transactions">Ver todos</a></div>{transactions.slice(0,5).map(t=><div className="list-row" key={t.id}><div><strong>{t.description}</strong><span>{t.transaction_date} · {t.status}</span></div><strong className={t.type==='INCOME'?'income':''}>{t.type==='INCOME'?'+':'−'} {formatCurrency(Number(t.amount))}</strong></div>)}{transactions.length===0&&<p className="muted">Nenhum lançamento neste mês.</p>}</section></>; }
