create extension if not exists "pgcrypto";

create type public.workspace_role as enum ('OWNER', 'MEMBER');
create type public.transaction_type as enum ('INCOME', 'EXPENSE', 'TRANSFER');
create type public.transaction_status as enum ('PENDING', 'PAID', 'RECEIVED', 'OVERDUE', 'CANCELLED');
create type public.payment_method as enum ('PIX', 'DEBIT', 'CASH', 'CREDIT_CARD');
create type public.category_type as enum ('INCOME', 'EXPENSE', 'BOTH');
create type public.invoice_status as enum ('OPEN', 'CLOSED', 'PAID');
create type public.recurrence_frequency as enum ('MONTHLY', 'WEEKLY', 'YEARLY');
create type public.fuel_type as enum ('GASOLINE', 'ETHANOL', 'DIESEL', 'GNV');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null, avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workspaces (id uuid primary key default gen_random_uuid(), name text not null, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workspace_members (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role public.workspace_role not null default 'MEMBER', created_at timestamptz not null default now(), unique(workspace_id, user_id));
create table public.accounts (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), owner_user_id uuid references public.profiles(id), name text not null, type text not null, initial_balance numeric(14,2) not null default 0, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), name text not null, type public.category_type not null, icon text, active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id, name));
create table public.credit_cards (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), owner_user_id uuid references public.profiles(id), name text not null, brand text, limit_amount numeric(14,2) not null check(limit_amount >= 0), closing_day integer not null check(closing_day between 1 and 31), due_day integer not null check(due_day between 1 and 31), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.credit_card_invoices (id uuid primary key default gen_random_uuid(), credit_card_id uuid not null references public.credit_cards(id), reference_month date not null, closing_date date not null, due_date date not null, status public.invoice_status not null default 'OPEN', paid_at timestamptz, payment_transaction_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(credit_card_id, reference_month));
create table public.recurrences (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), owner_user_id uuid references public.profiles(id), type public.transaction_type not null check(type <> 'TRANSFER'), frequency public.recurrence_frequency not null default 'MONTHLY', day_of_month integer check(day_of_month between 1 and 31), start_date date not null, end_date date, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.recurrence_versions (id uuid primary key default gen_random_uuid(), recurrence_id uuid not null references public.recurrences(id) on delete cascade, description text not null, amount numeric(14,2) not null check(amount > 0), category_id uuid references public.categories(id), payment_method public.payment_method, account_id uuid references public.accounts(id), credit_card_id uuid references public.credit_cards(id), valid_from date not null, valid_until date, created_at timestamptz not null default now(), check(valid_until is null or valid_until >= valid_from));
create table public.installment_groups (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), description text not null, original_amount numeric(14,2) not null check(original_amount > 0), installments integer not null check(installments > 1), created_at timestamptz not null default now());
create table public.transactions (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), owner_user_id uuid references public.profiles(id), type public.transaction_type not null, description text not null, amount numeric(14,2) not null check(amount > 0), category_id uuid references public.categories(id), transaction_date date not null, competence_date date not null, due_date date, settled_at timestamptz, status public.transaction_status not null default 'PENDING', payment_method public.payment_method, account_id uuid references public.accounts(id), credit_card_id uuid references public.credit_cards(id), credit_card_invoice_id uuid references public.credit_card_invoices(id), recurrence_id uuid references public.recurrences(id), recurrence_version_id uuid references public.recurrence_versions(id), is_recurrence_override boolean not null default false, is_invoice_payment boolean not null default false, installment_group_id uuid references public.installment_groups(id), installment_number integer, installment_total integer, transfer_group_id uuid, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check((type = 'TRANSFER') or category_id is not null or is_invoice_payment), check((payment_method = 'CREDIT_CARD' and credit_card_id is not null) or (payment_method in ('PIX','DEBIT','CASH') and account_id is not null) or payment_method is null), check(installment_number is null or (installment_number between 1 and installment_total and installment_total > 1)));
create table public.vehicles (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), owner_user_id uuid references public.profiles(id), name text not null, plate text, brand text, model text not null, year integer, current_odometer numeric(12,1), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.vehicle_fuel_types (id uuid primary key default gen_random_uuid(), vehicle_id uuid not null references public.vehicles(id) on delete cascade, fuel_type public.fuel_type not null, created_at timestamptz not null default now(), unique(vehicle_id, fuel_type));
create table public.fuel_entries (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces(id), vehicle_id uuid not null references public.vehicles(id), transaction_id uuid not null unique references public.transactions(id), fuel_type public.fuel_type not null, fuel_date date not null, odometer numeric(12,1) not null check(odometer >= 0), liters numeric(12,3) not null check(liters > 0), total_amount numeric(14,2) not null check(total_amount > 0), price_per_liter numeric(14,4) generated always as (total_amount / liters) stored, full_tank boolean not null default false, gas_station text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index transactions_workspace_date_idx on public.transactions(workspace_id, transaction_date desc);
create index transactions_competence_idx on public.transactions(workspace_id, competence_date desc);
create index transactions_account_idx on public.transactions(account_id);
create index transactions_category_idx on public.transactions(category_id);
create index transactions_status_idx on public.transactions(workspace_id, status);
create index transactions_invoice_idx on public.transactions(credit_card_invoice_id);
create index fuel_entries_vehicle_date_idx on public.fuel_entries(vehicle_id, fuel_date desc);
create index fuel_entries_workspace_idx on public.fuel_entries(workspace_id);
create index recurrence_versions_lookup_idx on public.recurrence_versions(recurrence_id, valid_from desc);
create index invoices_status_idx on public.credit_card_invoices(status);
